# 小テスト②（25点）
### 作成：Sクラスコンテンツ管理チーム

今回は、[Wine Quality Data Set](https://archive.ics.uci.edu/ml/datasets/wine+quality)を用いてワインの品質予測を行う。  
ワインのデータ数は1599個、説明変数は11変数、目的変数の'quality'は10段階(実際の分布は3~8)で評価されている。  

| | 変数 | 詳細 |
| - | ---- | ---- |
|1| fixed acidity | 酒石酸濃度 | 
|2| volatile acidity | 酢酸濃度 | 
|3|citric acid | クエン酸濃度 | 
|4| residual sugar | 残糖濃度 | 
|5| chlorides | 塩化ナトリウム濃度 |  
|6| free sulfur dioxide | 遊離SO2濃度 | 
|7| total sulfur dioxide | 総SO2濃度 | 
|8| density | 密度 | 
|9| pH | pH | 
|10| sulphates	 | 硫化カリウム濃度| 
|11| alcohol | アルコール濃度 | 
|12| quality | ワインの品質 | 

In [1]:
# 必要なライブラリを読み込み
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

## 第１問　回帰（11点）

ワインデータセットを用いて、ワインの品質を回帰分析によって予測する問題を考える。  

In [25]:
# データをインポート
data1 = pd.read_csv('test_data.csv')
data1.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

### 1) 説明変数と目的変数'quality'との相関係数行列を出力し、相関の強い変数を順番に6つ答えてください。（2点）

In [26]:
data1.corr()[['quality']].apply(lambda s: abs(s)).sort_values(by = 'quality',ascending = False)

quality
quality               1.000000
alcohol               0.476166
volatile acidity      0.390558
sulphates             0.251397
citric acid           0.226373
total sulfur dioxide  0.185100
density               0.174919
chlorides             0.128907
fixed acidity         0.124052
pH                    0.057731
free sulfur dioxide   0.050656
residual sugar        0.013732

In [27]:
# 相関係数行列を出力(1点)
data1.corr()

fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000         -0.256131     0.671703   
volatile acidity          -0.256131          1.000000    -0.552496   
citric acid                0.671703         -0.552496     1.000000   
residual sugar             0.114777          0.001918     0.143577   
chlorides                  0.093705          0.061298     0.203823   
free sulfur dioxide       -0.153794         -0.010504    -0.060978   
total sulfur dioxide      -0.113181          0.076470     0.035533   
density                    0.668047          0.022026     0.364947   
pH                        -0.682978          0.234937    -0.541904   
sulphates                  0.183006         -0.260987     0.312770   
alcohol                   -0.061668         -0.202288     0.109903   
quality                    0.124052         -0.390558     0.226373   

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity               0.114777   0.093705            -0.153794   
volatile acidity            0.001918   0.061298            -0.010504   
citric acid                 0.143577   0.203823            -0.060978   
residual sugar              1.000000   0.055610             0.187049   
chlorides                   0.055610   1.000000             0.005562   
free sulfur dioxide         0.187049   0.005562             1.000000   
total sulfur dioxide        0.203028   0.047400             0.667666   
density                     0.355283   0.200632            -0.021946   
pH                         -0.085652  -0.265026             0.070377   
sulphates                   0.005527   0.371260             0.051658   
alcohol                     0.042075  -0.221141            -0.069408   
quality                     0.013732  -0.128907            -0.050656   

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                    -0.113181  0.668047 -0.682978   0.183006   
volatile acidity                  0.076470  0.022026  0.234937  -0.260987   
citric acid                       0.035533  0.364947 -0.541904   0.312770   
residual sugar                    0.203028  0.355283 -0.085652   0.005527   
chlorides                         0.047400  0.200632 -0.265026   0.371260   
free sulfur dioxide               0.667666 -0.021946  0.070377   0.051658   
total sulfur dioxide              1.000000  0.071269 -0.066495   0.042947   
density                           0.071269  1.000000 -0.341699   0.148506   
pH                               -0.066495 -0.341699  1.000000  -0.196648   
sulphates                         0.042947  0.148506 -0.196648   1.000000   
alcohol                          -0.205654 -0.496180  0.205633   0.093595   
quality                          -0.185100 -0.174919 -0.057731   0.251397   

                       alcohol   quality  
fixed acidity        -0.061668  0.124052  
volatile acidity     -0.202288 -0.390558  
citric acid           0.109903  0.226373  
residual sugar        0.042075  0.013732  
chlorides            -0.221141 -0.128907  
free sulfur dioxide  -0.069408 -0.050656  
total sulfur dioxide -0.205654 -0.185100  
density              -0.496180 -0.174919  
pH                    0.205633 -0.057731  
sulphates             0.093595  0.251397  
alcohol               1.000000  0.476166  
quality               0.476166  1.000000

#### 相関の強い変数を順番に6つ答えてください。（1点）
相関が強いものから、(絶対値で考えて)
alcohol,
volatile acidity,
sulphates,
citric acid,
total sulfur dioxide,
density,

In [28]:
data1.corr()[['quality']].apply(lambda s: abs(s)).sort_values(by = 'quality',ascending = False).index

Index(['quality', 'alcohol', 'volatile acidity', 'sulphates', 'citric acid',
       'total sulfur dioxide', 'density', 'chlorides', 'fixed acidity', 'pH',
       'free sulfur dioxide', 'residual sugar'],
      dtype='object')

### 2) 以下の指示にしたがってデータの前処理を行ってください。（4点）

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Xに選んだ６つの変数、yに'quality' の値を代入してください。(2点)
X = data1[['alcohol', 'volatile acidity', 'sulphates', 'citric acid','total sulfur dioxide', 'density']].values
y = data1[['quality']].values
# X, yに対してデータの標準化を行ってください。(1点)
ss1 = StandardScaler()
ss2 = StandardScaler()
X_std = ss1.fit_transform(X)
y_std = ss2.fit_transform(y)
# ホールドアウト法でデータを分割してください。ただし、trainデータの割合は75%とする。（1点）
X_train, X_test, y_train, y_test = train_test_split(X_std,y_std,test_size=0.25)

C:\Users\Rofan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


### 3) 以下の指示にしたがって線形回帰モデルを学習させ、性能評価を行ってください。（3点）

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error as mse
# 線形回帰インスタンスを生成
lr_std = LinearRegression()
# 重回帰分析の学習を行ってください。(1点)
lr_std.fit(X_train,y_train)
# trainデータとtestデータのそれぞれについてRMSE(平均二乗誤差の平方根)を出力してください。（2点）
print('RMSE')
print('train: %.3f' % (mse(y_train, lr_std.predict(X_train)) ** (1/2)))
print('test : %.3f' % (mse(y_test, lr_std.predict(X_test)) ** (1/2)))

RMSE
train: 0.803
test : 0.836


### 4) 学習モデルの標準変回帰係数を出力し、重要度の高い変数を順番に6つ答えてください。（2点）

In [32]:
# 標準変回帰係数の出力(1点)
lr_std.coef_


array([[ 0.41626225, -0.29292577,  0.12547566, -0.05351916, -0.05905393,
         0.01399866]])

#### 重要度の強い変数を順番に6つ答えてください。(Markdown形式で記入)
重要度が強いものから、

- alcohol
- volatile acidity
- sulphates
- total sulfur dioxide
- citric acid
- density

## 第2問　分類（9点）

ワインデータセットを用いて、'quality'が６以上の時は1、５以下の時は0として、２種類のワインに分類することを考える。

In [23]:
# データのインポート
data2 = pd.read_csv('test_data.csv')
# 'quality' が６以上の時は「１」、５以下の時は「０」に置き換える。
data2['quality'] = np.where(data2['quality'] > 5, 1, 0)
data2.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        0  
1      9.8        0  
2      9.8        0  
3      9.8        1  
4      9.4        0

### 1) 以下の指示にしたがってデータの前処理を行ってください。（4点）

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Xに全ての説明変数, yに'quality'の値を代入してください。(2点)
# ただし、scikit-learnの仕様により、yを１列のベクトルに変換しなければならない事に注意してください。(.reshape(-1))
X = data2[['alcohol', 'volatile acidity', 'sulphates', 'citric acid',
       'total sulfur dioxide', 'density', 'chlorides', 'fixed acidity', 'pH',
       'free sulfur dioxide', 'residual sugar']].values
y = data2[['quality']].values
# Xに対してデータの標準化を行ってください。(1点)
ss = StandardScaler()
X_std = ss.fit_transform(X)
# ホールドアウト法でデータを分割してください。ただし、trainデータの割合は65%とする。(1点)
X_train, X_test, y_train, y_test = X_train, X_test, y_train, y_test = train_test_split(X_std,y,test_size=0.35)

### 2) 以下の指示にしたがってロジスティック回帰モデルを学習させ、性能評価を行ってください。（3点）

In [35]:
from sklearn.linear_model import LogisticRegression
# ロジスティック回帰インスタンスの生成(逆正則化パラメータ 「C」は、デフォルトの1.0とする)
LR = LogisticRegression(C=1.0)
# ロジスティック回帰モデルの学習を行ってください。(1点)
LR.fit(X_std,y)
# trainデータとtestデータのそれぞれについて正答率(score)を出力してください。(2点)
print('train acc: %.3f' % LR.score(X_train, y_train))
print('test acc: %.3f' % LR.score(X_test, y_test))


train acc: 0.737
test acc: 0.755


C:\Users\Rofan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### 3) 以下の指示にしたがって、testデータの中での良いワインの割合を求めてください。（2点）
＜ストーリー＞  
ワイン販売を行うA社は、今回作成したロジスティック回帰のモデルを仕入れに活用しようと考えた。しかし、現状モデルでは、普通のワインも良いワインであると予測してしまうという問題があった。そこで予測するときに良いワインであるという予測確率が80%を超えたワインのみを仕入れ対象に絞ることにした。

In [ ]:
# testデータ全てに対して1（良いワイン）であるという予測確率を出力してください。(1点)


In [ ]:
# 予測確率が80%を超えたものを良いワインと再定義し、testデータ全体の中で良いワインの割合を出力してください。（1点）


## 第3問 クラス（5点）
名前と血液型と体重と身長をインスタンス変数とし、BMIを計算をするcalc_bmiメソッドと、指標に基づいて体型を評価するeval_bmiメソッドと、情報を表示するshowメソッドをもつクラス「Person」を作成したい。BMIは体重 $w[kg]$, 身長$h[m]$とすると、$$BMI = w/h^2$$と表すことができる。また、$$18.5 \leq BMI < 25.0$$を標準BMIとし、標準BMI未満は痩せ型、標準BMI以上は肥満型とする。



ここでは、例えば、名前が○○, 血液型が?型, 体重45.0kg, 身長1.50mの人は
```
○○さんの血液型は?型で、BMIは20.00で標準体型です。
```
と表示されるようにしたい。  
以下のコードを埋めてください。

In [36]:
class Person:
    def __init__(self, name, blood_type, weight, height):
        # ここに入力してください。（1点）
        self.name = name
        self.blood_type = blood_type
        self.weight = weight
        self.height = height
        
    
    def calc_bmi(self):
        # ここに入力してください。（1点）
        return self.weight / (self.height**2)
        
    
    def eval_bmi(self):
        # ここに入力してください。（1点）
        b = self.bmi()
        if b>=25:
            s = '肥満型'
        elif b>=18.5:
            s = '標準体型'
        else:
            s = '痩せ型'
        return s
        
    def show(self):
        # 上の例のように出力(BMIは小数点以下2桁まで表示)。
        # ここに入力してください。（1点）
        print('{}さんの血液型は{}型で、BMIは{}で{}です。BMIは{:.1f}で'.format(self.name(),self.blood_type(),self.calc_bmi(),self.eval_bmi())

# 人名が「河内」、血液型は「O型」、体重は「60.0kg」、 身長は「1.75m」インスタンスを生成して、show()で表示させてください。（1点）


SyntaxError: unexpected EOF while parsing (<ipython-input-36-30a1fac6068b>, line 31)